apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poetbio-deployment-name
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: poetbio-label
    spec:
      containers:
        - image: cgos/poetbio
          imagePullPolicy: Always
          name: poetbio
          ports:
            - containerPort: 8888