apiVersion: v1
kind: Service
metadata:
  name: poetrypage-service-name
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: poetrypage-label