apiVersion: v1
kind: Service
metadata:
  name: poemprovider-service-name
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8181
  selector:
    app: poemprovider-label